---
- name: install_tmux
  homebrew: name=tmux state=present

- name: Install tmux-switch-session
  get_url: >
    url=https://raw.githubusercontent.com/mislav/dotfiles/master/bin/tmux-switch-session
    dest=/usr/local/bin/tmux-switch-session
    mode=0755

- name: Install tmuxinator gem
  gem: name=tmuxinator state=latest