---
- name: Ensure the user SSH directory exists
  file: >
    dest=/Users/{{ ansible_user_id }}/.ssh
    state=directory
- name: Ensure user known hosts file exists
  copy: >
    src=known_hosts
    dest=/Users/{{ ansible_user_id }}/.ssh/known_hosts
- name: Ensure the Ansible downloads directory exists
  file: >
    path={{ downloads_directory }}
    state=directory
- name: Ensure user known hosts file exists
  copy: >
    src=known_hosts
    dest=/Users/{{ ansible_user_id }}/.ssh/known_hosts