---
- name: Ensure the user SSH directory exists
  file: >
    dest=/Users/{{ ansible_user_id }}/.ssh
    state=directory
- name: Ensure user known hosts file exists
  copy: >
    src=known_hosts
    dest=/Users/{{ ansible_user_id }}/.ssh/known_hosts
- name: Ensure the Ansible downloads directory exists
  file: >
    path={{ downloads_directory }}
    state=directory
- name: Ensure user known hosts file exists
  copy: >
    src=known_hosts
    dest=/Users/{{ ansible_user_id }}/.ssh/known_hosts

# - name: copy pem files from a Dropbox directory to ~/.ssh
#   copy: >
#     src=/Users/{{ ansible_user_id}}/Dropbox/ssh/*.pem
#     dest=/Users/{{ ansible_user_id}}/.ssh
    
- name: copy each file over that matches the given pattern
  copy: src={{ item }} dest=/Users/{{ ansible_user_id}}/.ssh
  with_fileglob:
  - /Users/{{ ansible_user_id}}/Dropbox/ssh/*.pem     
    
- name: chmod 400 all the pem files transferred over so they have the correct permissions for aws
  shell: chmod 400 /Users/{{ ansible_user_id}}/.ssh/*.pem 

- name: copy over ssh config file
  copy: >
    src=/Users/{{ ansible_user_id}}/Dropbox/ssh/config
    dest=/Users/{{ ansible_user_id}}/.ssh
- name: Copy private SSH key rsa
  copy: >
    src=/Users/{{ ansible_user_id }}/Dropbox/ssh/id_rsa
    dest=/Users/{{ ansible_user_id }}/.ssh/id_rsa
    mode=0400
- name: Copy public SSH key rsa
  copy: >
    src=/Users/{{ ansible_user_id }}/Dropbox/ssh/id_rsa.pub
    dest=/Users/{{ ansible_user_id }}/.ssh/id_rsa.pub
    mode=0444
- name: Copy private SSH key dsa
  copy: >
    src=/Users/{{ ansible_user_id }}/Dropbox/ssh/id_dsa
    dest=/Users/{{ ansible_user_id }}/.ssh/id_dsa
    mode=0400
- name: Copy public SSH key dsa
  copy: >
    src=/Users/{{ ansible_user_id }}/Dropbox/ssh/id_dsa.pub
    dest=/Users/{{ ansible_user_id }}/.ssh/id_dsa.pub
    mode=0444

#    #ln -s ~/Dropbox ~/me
#http://docs.ansible.com/ansible/latest/shell_module.html
# - name: symlink to ~/me
#   shell: ln -s ~/Dropbox ~/me
#   args:
#     executable: /bin/bash
   
   
